### ISSUE TITLE
what return protocol/openid-connect/certs?

### ISSUE THREAD

**Issue by solinad21** [jomatt/spring-boot-multitenant-sample#1]
i am testing your sample with mode jwt,

and i do not know what return this: "...../protocol/openid-connect/certs"

what this endpoint "...../protocol/openid-connect/certs" expects to receive? jwt, jwk, json? what structures?

**Comment by solinad21** [comment]
the endpoint run ok but i do not know what return?

@GetMapping("/protocol/openid-connect/certs")
    public String getCerts() {
        return "tenant1"; // not work, ?????????
    }

**Comment by jomatt** [comment]
If you want to use JWT mode, you need to have an OAuth2 authorization server that issues JWT tokens. You could either include [Spring Authorization Server](https://spring.io/projects/spring-authorization-server) into your app or you can use a dedicated tool like [Keycloak](https://www.keycloak.org) or any other OAuth2 compatible authorization server.

I am currently working on preparing another sample where I integrate Keycloak into the application stack. In this example it will get clear how the JWT mode is used.

**Comment by solinad21** [comment]
i await for your new demo, in the while, i am modifying your last demo for work with tokens using the header option. 

the work go ok.

**Comment by jomatt** [comment]
@solinad21 I have added a sample which uses JWT resolution mode. You can activate it with the Spring `prod` profile
