### ISSUE TITLE
Spring boot 3

### ISSUE THREAD

**Issue by khocef** [jomatt/spring-boot-multitenant-sample#3]
Hello and thanks for this lib.

Any plans to migrate to the latest version of spring ?

**Comment by jomatt** [comment]
Hi @khocef. Thanks for your interest. It's on my todo list but currently I don't have a specific target date to add Spring Boot 3 support. If you are interested in collaborating, feel free to send me a PR and I will review it.

**Comment by jomatt** [comment]
@khocef I'm currently working on the Spring Boot 3 update here: https://github.com/quantics-io/multitenant-oauth2-spring-boot-starter/pull/13. Please let me know if you encounter any problems during testing. I'm planning to release verson `0.4` of the library soon.

Here is the PR to verify the changes: #6
